ALTER TABLE negocio
ADD COLUMN fecha_inicio VARCHAR(50),
ADD COLUMN registrado_camara BOOLEAN DEFAULT FALSE,
ADD COLUMN direccion VARCHAR(255),
ADD COLUMN pagina_web VARCHAR(255),
ADD COLUMN ciudad VARCHAR(100),
ADD COLUMN imagen BYTEA;
